### ISSUE TITLE
PageOne 里面存在banner左右滚动图片上下拉问题

### ISSUE THREAD

**Issue by Doinbe** [ysnows/DoubleScrollVIew#13]
PageOne 里面存在banner左右滚动图片，PageOne 在banner区域的上下滑动是拖动真个PageOne显示的页面在动。比如在banner区域的向上滑动，直接跳到PageTwo页面了，并不是滑动显示完PageOne页面的所有内容再显示PageTwo的类容。这是banner滑动于这控件滑动事件冲突了？？？

**Comment by Doinbe** [comment]
应该是 ViewPager和ScrollView冲突

**Comment by ysnows** [comment]
嗯，仔细找找，多试试

**Comment by niray** [comment]
@ysnows  @Doinbe  我现在跟你的问题一样诶,只要是在有点击事件或者滑动事件的小组件上进行滑动,都会直接滑动到第二个WebView,,  请问怎么解决的焦点问题

**Comment by ysnows** [comment]
@niray @Doinbe  用behavior重新写了，这个问题解决了，同步下最新的代码试试
