### ISSUE TITLE
底部的ScrollView（或WebView），无法正常向下滚动内容

### ISSUE THREAD

**Issue by UsherBaby** [ysnows/DoubleScrollVIew#2]

**Comment by ysnows** [comment]
收到了，会抽时间解决一下的，thank you

在 2015-09-11 16:19:33，"UsherBaby" <notifications@github.com> 写道：

**Comment by CharlieZheng** [comment]
在ScrollViewPageOne中，move事件，判断是否交给RootScrollView处理后续事件的条件：if(Ys < 0 && padding == limit)改为if(Ys < 0 && padding <= limit)貌似会好点。
同样的，在Two中，把条件改为if(Ys > 0 && t <= 0)会好点。望采纳。
