### ISSUE TITLE
下拉不灵，显示ScrollViewPageOne的Padding

### ISSUE THREAD

**Issue by CharlieZheng** [ysnows/DoubleScrollVIew#3]
在ScrollViewPageOne中，move事件，判断是否交给RootScrollView处理后续事件的条件：if(Ys < 0 && padding == limit)改为if(Ys < 0 && padding <= limit)貌似会好点。
同样的，在Two中，把条件改为if(Ys > 0 && t <= 0)会好点。望采纳。

**Comment by ysnows** [comment]
收到了，会抽时间试一下的，thank you
