### ISSUE TITLE
有个问题请教一下。

### ISSUE THREAD

**Issue by lywhlao** [ysnows/DoubleScrollVIew#4]
您好，我最近研究了一下你的代码，有个问题想请教一下，SlidingMenu类中的onMeasure方法，对于这两行代码：
             //设置两个子View的高度为手机的高度
            wrapperMenu.getLayoutParams().height = mScreenHeight;
            wrapperContent.getLayoutParams().height = mScreenHeight;
为什么要将这两个scrollView的高度设置为屏幕的高度？

**Comment by ysnows** [comment]
必须设置一个固定的高度，不一定是屏幕高度
