### ISSUE TITLE
关于PageTwoWebView

### ISSUE THREAD

**Issue by YeChenLiu** [ysnows/DoubleScrollVIew#7]
如果直接用PageTwoWebView 了话 一进去就是显示PageTwoWebView  而PageOne还在屏幕外
 而我吧DoubleSrcollViewWrapper 里面的onLayout（） 里面的判断去掉直接 使用this.scrollTo(0, 0);  暂时解决了   但是这是为什么呢

**Comment by ysnows** [comment]
焦点问题吧
